version: '3.8'

services:
  gateway:
    container_name: backend-sht-gateway
    platform: linux/amd64
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    env_file:
      - backend/_env/.env
      - backend/_env/gateway/.env.local
    build:
      context: './'
      dockerfile: backend/docker/gateway/Dockerfile
    ports:
      - '8005:8005'
  acl:
    container_name: backend-sht-acl
    platform: linux/amd64
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    env_file:
      - backend/_env/.env
      - backend/_env/acl/.env.local
    build:
      context: './'
      dockerfile: backend/docker/acl/Dockerfile
    ports:
      - '8006:8006'
  shtner:
    container_name: backend-sht-shtner
    platform: linux/amd64
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    env_file:
      - backend/_env/.env
      - backend/_env/shtner/.env.local
    build:
      context: './'
      dockerfile: backend/docker/shtner/Dockerfile
    ports:
      - '8007:8007'
  worker:
    container_name: backend-sht-worker
    platform: linux/amd64
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    env_file:
      - backend/_env/.env
      - backend/_env/worker/.env.local
    build:
      context: './'
      dockerfile: backend/docker/worker/Dockerfile
    ports:
      - '8008:8008'
