name: develop-repo
author: Funmi Ayinde
description: Get dev ops repo

inputs:
  inputs:
    description: 'Repository'


runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download Repo to Artifact
