name: set-aws-envs
author: Funmi Ayinde
description: A generic action to get app global based envs

inputs:
  config-file:
    required: true
    default: "configs/cloud.json"

runs:
  using: 'composite'
  steps:
    -name: Checkout
    uses: actions/checkout@v3