import Frame_5 from './frame_5';
import Frame_1 from './frame_1';
import Frame_3 from './frame_3';
import Frame_8 from './frame_8';
import Frame_2 from './frame_2';
import Frame_6 from './frame_6';
import Frame_9 from './frame_9';
import Frame_7 from './frame_7';
import Frame_4 from './frame_4';
export { Frame_5, Frame_1, Frame_2, Frame_6, Frame_8, Frame_9, Frame_7, Frame_3, Frame_4 };
