import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import { PageLayout, ShtcutProvider } from '@shtcut-ui/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="font-poppins">
                <ShtcutProvider attribute="class" defaultTheme="dark" enableSystem={false} disableTransitionOnChange>
                    <PageLayout className="bg-white-90">{children}</PageLayout>
                    {/* {children} */}
                </ShtcutProvider>
            </body>
        </html>
    );
}
