apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-dpl
  labels:
    # Project ID
    app: ${APP_NAME}

spec:
  # Run one instances of our application
  replicas: ${REPLICA}
  selector:
    matchLabels:
      app: ${APP_NAME}-pod
  template:
    metadata:
      labels:
        app: ${APP_NAME}-pod
