name: CI FLOW

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
      AWS_DEFAULT_REGION:
        description: 'AWS Default Region'
        required: true
      GH_CUSTOM_TOKEN:
        description: 'GitHub Custom Token'
        required: true
      CI_SECRET:
        description: 'CI Secret'
    inputs:
      is_workflow:
        required: true
        type: boolean
        default: false
      owner:
        required: true
        type: boolean
      service:
        required: true
        type: string
      name:
        required: true
        type: string
      project:
        required: true
        type: string
      region:
        required: true
        type: string
      repository:
        required: true
        type: string
      instance_type:
        type: string
      hostname-format:
        required: true
        type: string
      environment:
        required: true
        type: string
      namespace:
        required: true
        type: string
      port:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      probe_url:
        type: string
      buildCommand:
        type: string
      unitCommand:
        type: string
      e2eTestCommand:
        type: string
      app_secret:
        type: string

permissions:
  id-tokens: write
  contents: read


jobs:
  info:
    name: CI workflow for ${{ inputs.service }}
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        run: |
          echo "Service name : ${{ inputs.service }}"
  changes:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [ info ]
    name: Test changes-files for ${{ inputs.service }}
    outputs:
      file-changes: ${{ steps.changed-files.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List changed files
        run: |
          for files in ${{ steps.changed-file.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
          
        
      


