name: DEPLOY STG

on:
  push:
    branches:
      - "develop"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


permissions:
  id-token: write
  contents: read


env:
  owner: "Shtcut"
  repository: "ShtcutDevOps"
  project: "Shtcut"
  region: "us-east-1"
  domain: "shtcut.link"
  namespace: "dev"
  environment: "dev"
  app_secret: "shtcut-dev-secret"
  probe_url: "/api/v1/ping"
  port: 7000

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      file-changes: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List all changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            backed/src/**
            .git